pipeline {
    agent any
    stages {
        stage ('Build') {
            steps {
                sh 'printenv'
                sh 'docker build -t testimage .'
            }
        }
        stage ('Publish ECR'){
            steps {
                withEnv (["AWS_ACCESS_KEY_ID=${env.AWS_ACCESS_KEY_ID}", "AWS_SECRET_ACCESS_KEY=${env.AWS_SECRET_ACCESS_KEY}", "AWS_DEFAULT_REGION=${env.AWS_DEFAULT_REGION} "]) {
                    sh 'docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 036249831903.dkr.ecr.us-east-1.amazonaws.com'
                    sh 'docker build -t demoapp/frontendservice .'
                    sh 'docker tag demoapp/frontendservice:latest 036249831903.dkr.ecr.us-east-1.amazonaws.com/demoapp/frontendservice:latest'
                    sh 'docker push 036249831903.dkr.ecr.us-east-1.amazonaws.com/demoapp/frontendservice:latest'
                }
            }
        }
    }
}